services:
  find-a-friend-api-pg:
    image: bitnami/postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findafrienddb
      
  find-a-friend-api-pg-test:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findafrienddb_test
